---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/delta-producer-background-jobs-initiator
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
---
kind: pipeline
type: docker
name: release
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/delta-producer-background-jobs-initiator
    dry_run: true
    purge: true
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/delta-producer-background-jobs-initiator
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: HhUJdxGi2Rx12SinOoHaznxQms0f9UBJyuaiqsr1+aEGi9Y725wSmg==
---
kind: secret
name: docker_password
data: 3NPvq+iS5kYwASIQX65eohTEWQRg0SUDeO4dB9vB7HVrR9h7vZ/KHikgRA12Eupf3z1VE/t2vZda1Yf2SkMEgg==
---
kind: signature
hmac: 7b12396c568f1b158e963381cb9cddaf3a13b59e1210c89aa8b982a34bdbb940

...
